name: nomo_webview
description: A supercharged WebView for Flutter apps
version: 0.1.0

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.3
  webview_flutter_wkwebview: ^3.15.0
  file_picker:
    path: packages/flutter_file_picker

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: app.nomo.plugin.nomo_webview
        pluginClass: NomoWebviewPlugin
      ios:
        pluginClass: NomoWebviewPlugin
        sharedDarwinSource: true
#      macos:
#        pluginClass: NomoWebviewPlugin
#        sharedDarwinSource: true