name: Nomo-Webview CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
   name: Static code analysis
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
         submodules: true
     - name: Update Submodules
       run: git submodule update --recursive --init
     - uses: subosito/flutter-action@v1
     - name: Lint analysis
       run: |
         flutter pub get
         flutter analyze
